--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1.pgdg120+1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: course; Type: TABLE; Schema: public; Owner: maxmakins
--

CREATE TABLE public.course (
    code character varying(255) NOT NULL,
    description character varying(255),
    grade character varying(255),
    name character varying(255),
    semester character varying(255),
    id bigint NOT NULL,
    details character varying(255)
);


ALTER TABLE public.course OWNER TO maxmakins;

--
-- Name: course_id_seq; Type: SEQUENCE; Schema: public; Owner: maxmakins
--

ALTER TABLE public.course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: maxmakins
--

CREATE TABLE public.project (
    name character varying(255) NOT NULL,
    description character varying(255),
    github_link character varying(255),
    public_link character varying(255),
    id bigint NOT NULL
);


ALTER TABLE public.project OWNER TO maxmakins;

--
-- Name: project_id_seq; Type: SEQUENCE; Schema: public; Owner: maxmakins
--

ALTER TABLE public.project ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_experience; Type: TABLE; Schema: public; Owner: maxmakins
--

CREATE TABLE public.work_experience (
    id bigint NOT NULL,
    company character varying(255),
    location character varying(255),
    logo character varying(255),
    role character varying(255),
    "time" character varying(255)
);


ALTER TABLE public.work_experience OWNER TO maxmakins;

--
-- Name: work_experience_details; Type: TABLE; Schema: public; Owner: maxmakins
--

CREATE TABLE public.work_experience_details (
    work_experience_id bigint NOT NULL,
    detail text
);


ALTER TABLE public.work_experience_details OWNER TO maxmakins;

--
-- Name: work_experience_seq; Type: SEQUENCE; Schema: public; Owner: maxmakins
--

CREATE SEQUENCE public.work_experience_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.work_experience_seq OWNER TO maxmakins;

--
-- Data for Name: course; Type: TABLE DATA; Schema: public; Owner: maxmakins
--

COPY public.course (code, description, grade, name, semester, id, details) FROM stdin;
\.


--
-- Data for Name: project; Type: TABLE DATA; Schema: public; Owner: maxmakins
--

COPY public.project (name, description, github_link, public_link, id) FROM stdin;
Course Judge	Developing a website in order to give college students insights into specific classes at their respective universities by viewing the opinions of other students through a peer-review process concerning a specific course and/or professor.	https://github.com/maxm-akins/course-judge	https://coursejudge.com/	1
Personal Website	Developed a personal website to provide a more user-friendly view of my resume and demonstrate skills as a web developer. 	https://github.com/maxm-akins/personal-site	https://maxmakins.com/	2
Language Development Site	I assisted in converting an Objective C iOS app into a React-based website. This website helped young children develop their English and/or Spanish comprehension skills while allowing researchers to analyze the factors that contributed to learning.	\N	\N	3
\.


--
-- Data for Name: work_experience; Type: TABLE DATA; Schema: public; Owner: maxmakins
--

COPY public.work_experience (id, company, location, logo, role, "time") FROM stdin;
1	Bank of New York	Pittsburgh, PA	bny.png	Software Engineer Intern	June 2024 - August 2024
52	GrayMatter Systems	Warrendale, PA	graymatter.png	Software Engineer Intern	May 2022 - Febuary 2025
102	University of Pittsburgh’s FacetLab	Pittsburgh, PA	pitt.png	Web Developer Research Assistant	September 2022 - March 2023
152	University of Pittsburgh’s FacetLab	Pittsburgh, PA	pitt.png	Data Analyst Research Assistant	December 2021 - May 2022
\.


--
-- Data for Name: work_experience_details; Type: TABLE DATA; Schema: public; Owner: maxmakins
--

COPY public.work_experience_details (work_experience_id, detail) FROM stdin;
1	Completed production and pre-production coding tasks on two separate teams. Developed in C# .NET, SQL, Javascript, and Python across the two units. Gained experience in practicing Agile and participated in all of the various ceremonies. Applied the AI resources available at the firm to a feature that was incorporated into an existing application and released into production. The feature saved around ten hours a week for the business team.
52	Designed and continue to maintain an implementation of a full MERN (MongoDB, Express, React, Node.js) stack website for use within the company to apply standards to administrative and financial processes—authentication and authorization functions included with additional practices to maintain security. The website's functionality streamlines work processes and creates efficiency in the amount of one hour of work per use per employee.
52	 Project-managed the development of a partner company's new product. The project’s success provided GrayMatter with participation in the partner's annual conference, creating exposure to hundreds of new business opportunities.
52	Engineered and maintained the front end of an intra-company process web app using HTML, CSS, and Javascript.
102	Converted an existing Objective C iOS app into a MERN stack website. The website aims to teach children English or Spanish through an interactive story-like interface.
152	Utilized Python and programming libraries (e.g. Pandas, Matplotlib, and SciKit-Learn) to analyze large quantities of data to gain insight into student learning behavior.
\.


--
-- Name: course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxmakins
--

SELECT pg_catalog.setval('public.course_id_seq', 1, false);


--
-- Name: project_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxmakins
--

SELECT pg_catalog.setval('public.project_id_seq', 3, true);


--
-- Name: work_experience_seq; Type: SEQUENCE SET; Schema: public; Owner: maxmakins
--

SELECT pg_catalog.setval('public.work_experience_seq', 201, true);


--
-- Name: course course_pkey; Type: CONSTRAINT; Schema: public; Owner: maxmakins
--

ALTER TABLE ONLY public.course
    ADD CONSTRAINT course_pkey PRIMARY KEY (code);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: maxmakins
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (name);


--
-- Name: work_experience work_experience_pkey; Type: CONSTRAINT; Schema: public; Owner: maxmakins
--

ALTER TABLE ONLY public.work_experience
    ADD CONSTRAINT work_experience_pkey PRIMARY KEY (id);


--
-- Name: work_experience_details fk41c8ce5fyxgd3c8emw4kd218u; Type: FK CONSTRAINT; Schema: public; Owner: maxmakins
--

ALTER TABLE ONLY public.work_experience_details
    ADD CONSTRAINT fk41c8ce5fyxgd3c8emw4kd218u FOREIGN KEY (work_experience_id) REFERENCES public.work_experience(id);


--
-- PostgreSQL database dump complete
--

